services:
  backend:
    container_name: url_backend
    image: saathwik834/url-backend:1.0
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis
    restart: always
  postgres:
    image: postgres:15
    container_name: url_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: urls
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:7
    container_name: url_redis
    restart: always
  frontend:
    image: saathwik834/url-frontend:1.0
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  postgres_data: